/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../com.deepin.daemon.GraphicsDriver.xml -i graphicsdriverinterface.h -a graphicsdriveradaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "graphicsdriveradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GraphicsDriverAdaptor
 */

GraphicsDriverAdaptor::GraphicsDriverAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GraphicsDriverAdaptor::~GraphicsDriverAdaptor()
{
    // destructor
}

QString GraphicsDriverAdaptor::GetNewDriverName()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetNewDriverName
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetNewDriverName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString GraphicsDriverAdaptor::GetOldDriverName()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetOldDriverName
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetOldDriverName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString GraphicsDriverAdaptor::GetResolutionTitle()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetResolutionTitle
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetResolutionTitle", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool GraphicsDriverAdaptor::IsTestSuccess()
{
    // handle method call com.deepin.daemon.GraphicsDriver.IsTestSuccess
    bool out0;
    QMetaObject::invokeMethod(parent(), "IsTestSuccess", Q_RETURN_ARG(bool, out0));
    return out0;
}

void GraphicsDriverAdaptor::PrepareInstall(int resolutionId)
{
    // handle method call com.deepin.daemon.GraphicsDriver.PrepareInstall
    QMetaObject::invokeMethod(parent(), "PrepareInstall", Q_ARG(int, resolutionId));
}

void GraphicsDriverAdaptor::RealInstaller()
{
    // handle method call com.deepin.daemon.GraphicsDriver.RealInstaller
    QMetaObject::invokeMethod(parent(), "RealInstaller");
}

void GraphicsDriverAdaptor::TestInstall()
{
    // handle method call com.deepin.daemon.GraphicsDriver.TestInstall
    QMetaObject::invokeMethod(parent(), "TestInstall");
}

