/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../com.deepin.daemon.GraphicsDriver.xml -i graphicsdriverinterface.h -a graphicsdriveradaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "graphicsdriveradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GraphicsDriverAdaptor
 */

GraphicsDriverAdaptor::GraphicsDriverAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GraphicsDriverAdaptor::~GraphicsDriverAdaptor()
{
    // destructor
}

void GraphicsDriverAdaptor::CancelInstall()
{
    // handle method call com.deepin.daemon.GraphicsDriver.CancelInstall
    QMetaObject::invokeMethod(parent(), "CancelInstall");
}

QString GraphicsDriverAdaptor::GetCurrDriverName()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetCurrDriverName
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetCurrDriverName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString GraphicsDriverAdaptor::GetDevice()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetDevice
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetDevice", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString GraphicsDriverAdaptor::GetNewDriverName()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetNewDriverName
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetNewDriverName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString GraphicsDriverAdaptor::GetOldDriverName()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetOldDriverName
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetOldDriverName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString GraphicsDriverAdaptor::GetResolutionTitle()
{
    // handle method call com.deepin.daemon.GraphicsDriver.GetResolutionTitle
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetResolutionTitle", Q_RETURN_ARG(QString, out0));
    return out0;
}

void GraphicsDriverAdaptor::Install()
{
    // handle method call com.deepin.daemon.GraphicsDriver.Install
    QMetaObject::invokeMethod(parent(), "Install");
}

bool GraphicsDriverAdaptor::IsTestSuccess()
{
    // handle method call com.deepin.daemon.GraphicsDriver.IsTestSuccess
    bool out0;
    QMetaObject::invokeMethod(parent(), "IsTestSuccess", Q_RETURN_ARG(bool, out0));
    return out0;
}

void GraphicsDriverAdaptor::PrepareInstall(const QString &name, const QString &language)
{
    // handle method call com.deepin.daemon.GraphicsDriver.PrepareInstall
    QMetaObject::invokeMethod(parent(), "PrepareInstall", Q_ARG(QString, name), Q_ARG(QString, language));
}

void GraphicsDriverAdaptor::TestSuccess()
{
    // handle method call com.deepin.daemon.GraphicsDriver.TestSuccess
    QMetaObject::invokeMethod(parent(), "TestSuccess");
}

