.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 UnionTech Software Technology Co., Ltd.,
.\"
.TH "deepin-graphics-driver-manager "1" "2021-02-02" "deepin-graphics-driver-manager manpage"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" for manpage-specific macros, see man(7)

.SH NAME
deepin-graphics-driver-manager
