/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../com.deepin.daemon.GraphicsDriver.xml -p graphicsdriverproxy
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef GRAPHICSDRIVERPROXY_H
#define GRAPHICSDRIVERPROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.daemon.GraphicsDriver
 */
class ComDeepinDaemonGraphicsDriverInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.daemon.GraphicsDriver"; }

public:
    ComDeepinDaemonGraphicsDriverInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~ComDeepinDaemonGraphicsDriverInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> OldDriver()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("OldDriver"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getDevice()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getDevice"), argumentList);
    }

    inline QDBusPendingReply<int> getDeviceFlag()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getDeviceFlag"), argumentList);
    }

    inline QDBusPendingReply<int> getInstallStatus()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getInstallStatus"), argumentList);
    }

    inline QDBusPendingReply<> installDriver()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("installDriver"), argumentList);
    }

    inline QDBusPendingReply<bool> isTestSuccess()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("isTestSuccess"), argumentList);
    }

    inline QDBusPendingReply<QString> newDriver()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("newDriver"), argumentList);
    }

    inline QDBusPendingReply<> reboot()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("reboot"), argumentList);
    }

    inline QDBusPendingReply<> removeDriver()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("removeDriver"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void installDriverResult(int in0);
    void removeDriverResult(int in0);
};

namespace com {
  namespace deepin {
    namespace daemon {
      typedef ::ComDeepinDaemonGraphicsDriverInterface GraphicsDriver;
    }
  }
}
#endif
