#!/bin/bash
systemctl stop lightdm

# run this command again here to avoid disable overlayroot in service not work

. /usr/lib/deepin-graphics-driver-manager/common.sh

if [[ -z "${isInOverlayRoot}" ]]; then
    error_reboot "Overlayroot failed to mount for the second time" ${OVERLAYROOT_MOUNT_ERROR}
fi

overlayroot_disable

# file "/tmp/deepin-prime-gltest" is generated by install prime script 
# cause prime needs some special ENV to work so here to start the special script for gltest
# otherwise start gltest directly
if [[ -e ${PRIME_GLTEST_G} ]]; then
    ${PRIME_GLTEST_G}
else
    /usr/bin/xinit /usr/lib/deepin-graphics-driver-manager/gltest
fi

error_reboot "Gltest running failed" ${GLTEST_RUNNING_ERROR}